name: Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install uv (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          powershell -c "irm https://astral.sh/uv/install.ps1 | iex"
          echo "$env:USERPROFILE\.cargo\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install uv (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install system dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libegl1-mesa-dev \
            libxcb1-dev \
            libxcb-keysyms1-dev \
            libxcb-util1-dev \
            libxcb-icccm4-dev \
            libxcb-image0-dev \
            libxcb-render-util0-dev \
            libxcb-randr0-dev \
            libxcb-xinerama0-dev \
            libxkbcommon-x11-0 \
            xvfb

      - name: Install dependencies
        run: |
          uv pip install --system pyside6

      - name: Test core functionality
        run: |
          python test_imports.py

      - name: Test GUI imports (Linux with virtual display)  
        if: matrix.os == 'ubuntu-latest'
        run: |
          xvfb-run -a python -c "
          from src.ui.main_window import GlimpseViewer
          from src.version import get_version
          print(f'GUI imports successful on Linux with virtual display')
          print(f'Glimpse v{get_version()} - Full GUI test passed')
          "

      - name: Test GUI imports (Windows/macOS)
        if: matrix.os != 'ubuntu-latest' 
        run: |
          python -c "
          from src.ui.main_window import GlimpseViewer
          from src.version import get_version
          print(f'GUI imports successful on ${{ matrix.os }}')
          print(f'Glimpse v{get_version()} - Full GUI test passed')
          "